-- vim.cmd [[
-- set nocompatible              " be iMproved, required
-- filetype off                  " required
-- 
-- set rtp+=~/.vim/bundle/Vundle.vim
-- call vundle#begin()
-- 
-- Plugin 'VundleVim/Vundle.vim'
-- 
-- Plugin 'SirVer/ultisnips'
-- 
-- call vundle#end()      
-- ]]
